FROM node:alpine AS build
ARG DOMAIN
ARG PORT

WORKDIR /app
ENV appDir /app
COPY . ${appDir}
RUN yarn
RUN yarn build

FROM nginx:alpine
COPY --from=build --chown=nginx:nginx /app/build /usr/share/nginx/html
# RUN rm /etc/nginx/conf.d/default.conf
# COPY config/nginx/default.conf /etc/nginx/conf.d
# --------- /only for those using react router ----------
# expose port 80 to the outer world
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
