FROM node:alpine AS build
WORKDIR /app
ENV appDir /app
COPY . ${appDir}
RUN yarn
RUN yarn build

FROM nginx:alpine
ENV API_URL=""
COPY --from=build --chown=nginx:nginx /app/build /usr/share/nginx/html
COPY docker-entrypoint.sh generate_config_js.sh /
RUN chmod +x docker-entrypoint.sh generate_config_js.sh
ENTRYPOINT ["/docker-entrypoint.sh"]

