# docker-compose file used to deploy assosuite in a prodution environment
#   TODO: add traefik, networks management
version: '3.8'

services:
  proxy:
    image: traefik:v2.2
    command: --api.insecure=true --providers.docker
    ports:
      -  80:80
      -  8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend
      - frontend
  backend:
    image: "docker.pkg.github.com/tolstoyfafa/assosuite/backend:${APP_VERSION}"
    restart: always
    depends_on: 
      - mongo
    networks:
      - backend

  frontend:
    image: "docker.pkg.github.com/tolstoyfafa/assosuite/frontend:${APP_VERSION}"
    restart: always
    depends_on:
      - backend
    networks:
      - frontend  

  database:
    image: mongo
    restart: always
    networks:
      - backend  
  
volumes:
  db-data:

networks:
  backend:
  frontend:    
