# docker-compose file used to deploy assosuite in a prodution environment
#   TODO: add traefik, networks management
version: '3.8'

services:

  proxy:
    image: traefik:v2.2
    command: --api.insecure=true --providers.docker
    ports:
      -  80:80
      -  8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net-external
      - backend
      - frontend

  backend:
    image: "docker.pkg.github.com/tolstoyfafa/assos_suite/assos-backend:${APP_VERSION}"
    restart: always
    depends_on: 
      - database
    labels:
      - "traefik.http.routers.backend.rule=Host(`backend.docker.localhost`)"
      - "traefik.docker.network=assos-backend" 
      - "traefik.http.services.backend.loadbalancer.server.port=80" 
    networks:
      - backend

  frontend:
    image: "docker.pkg.github.com/tolstoyfafa/assosuite/assos-frontend:{APP_VERSION}"
    restart: always
    depends_on:
      - backend
    networks:
      - frontend
    labels:
       - "traefik.http.routers.backend.rule=Host(`frontend.docker.localhost`)" 
       - "traefik.docker.network=assos-backend"                                    
       - "traefik.http.services.backend.loadbalancer.server.port=80"             

  database:
    image: mongo:4.2
    restart: always
    networks:
      - backend  

networks:
  backend:
    internal: true
  frontend:
    internal: true
  net-external:
    internal: false
