# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.8'

# Define services
services:
  # App backend service
  backend_dev:
       # Configuration for building the docker image for the backend service
      build:
        context: ./backend # Use an image built from the specified dockerfile in the `polling-app-server` directory.
        dockerfile: Dockerfile
      ports:
        - "8081:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
      volumes:
        - ./backend:/root

   
     # Frontend Service 
  frontend_dev:
      build:
        context: ./frontend # Use an image built from the specified dockerfile in the `polling-app-client` directory.
        dockerfile: Dockerfile
      ports:
        - "9090:3000" # Map the exposed port 80 on the container to port 9090 on the host machine
      networks:
        - frontend
      volumes:
        - ./frontend:/usr/src/app
   
  # Database Service (Mysql)
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
   #networks:
    #  - backend  

  mail:
    image: tvial/docker-mailserver:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    ports:
     - "20025:25"
     - "20465:465"
     - "20143:143"
     - "20587:587"
     - "20993:993"
    volumes:
     - ./config/:/tmp/docker-mailserver/

    
volumes:
    db-data:

# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend:    
