# docker-compose file used to deploy assosuite in a prodution environment
#   TODO: add traefik, networks management
version: '3.8'

services:

  proxy:
    image: traefik:v2.2
    command: --api.insecure=true --providers.docker
    ports:
      -  80:80
      -  8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gateway-external
      - gateway-backend
      - gateway-frontend

  backend:
    image: "docker.pkg.github.com/tolstoyfafa/assos_suite/assos-backend:${APP_VERSION}"
    restart: always
    depends_on: 
      - mongo
    labels:
      - "traefik.http.routers.backend.rule=Host(`backend.docker.localhost`)"
      - "traefik.docker.network=gateway-backend" 
      - "traefik.http.services.backend.loadbalancer.server.port=80"
    networks:
      - gateway-backend
      - only-backend

  frontend:
    image: "docker.pkg.github.com/tolstoyfafa/assos_suite/assos-frontend:${APP_VERSION}"
    restart: always
    depends_on:
      - backend
    labels:
        - "traefik.http.routers.frontend.rule=Host(`frontend.docker.localhost`)" 
        - "traefik.docker.network=gateway-frontend"                                    
        - "traefik.http.services.frontend.loadbalancer.server.port=80"             
    networks:
        - gateway-frontend

  mongo:
    image: mongo
    restart: always
    networks:
      - only-backend

networks:
  gateway-backend:
    internal: true
  gateway-frontend:
    internal: true
  gateway-external:
    internal: false
  only-backend:
    internal: true
