version: "3.7"
services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mongo
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
  mongo:
      container_name: mongo
      image: mongo
      ports:
        - 27017:27017
  mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: domain.com
    container_name: mail
    ports:
      - "2505:25"
      - "1430:143"
    volumes:
      - ./config/:/tmp/docker-mailserver/
