# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.8'
services:
  backend_dev:
      build:
        context: ./backend
        dockerfile: Dockerfile
      ports:
        - "8081:8080"
      volumes:
        - ./backend:/root

  frontend_dev:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      ports:
        - "9090:3000"
      volumes:
        - ./frontend:/usr/src/app
   
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db

  mail:
    image: tvial/docker-mailserver:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    ports:
      - "20025:25"
      - "20143:143"
      - "20587:587"
      - "20993:993"
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - maillogs:/var/log/mail
      - ./config/:/tmp/docker-mailserver/
    env_file:
      - .env
      - env-mailserver
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always

volumes:
  maildata:
  mailstate:
  maillogs: